import prisma from "../libs/prismadb";
import getCurrentUser from "../actions/getCurrentUser";
import Listings from "../components/Listings";
import Link from "next/link";
//import Head from "next/head";

export default async function Home() {
  const listings = await prisma.listing.findMany();
  const count = await prisma.listing.count();
  // const countFuture = await prisma.listing.count({
  //   where: { status: "UPCOMING" },
  // });
  // const countPast = await prisma.listing.count({
  //   where: { status: "ENDED" },
  // });
  // const countLive = await prisma.listing.count({
  //   where: { status: "LIVE" },
  // });

  const currentUser = await getCurrentUser();

  return (
    <div className="m-auto pt-14 lg:pt-16 pb-4 max-w-5xl px-2">
      {/* <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/logo.png" />
      </Head> */}
      <div className="flex justify-between">
        <h2 className="text-md font-bold w-max inline-block">
          Total Auctions
          <span className="text-sm font-normal"> ({count})</span>{" "}
        </h2>
        {/* <h2 className="text-md font-bold w-max md:inline-block hidden">
          <Link href="/live/listings">Live Auctions</Link>
          <span className="text-sm font-normal"> ({countLive})</span>{" "}
        </h2>
        <h2 className="text-md font-bold w-max md:inline-block hidden">
          <Link href="/future/listings">Upcoming Auctions</Link>
          <span className="text-sm font-normal"> ({countFuture})</span>{" "}
        </h2>
        <h2 className="text-md font-bold w-max md:inline-block hidden">
          <Link href="/past/listings">Past Auctions</Link>
          <span className="text-sm font-normal"> ({countPast})</span>{" "}
        </h2> */}
      </div>

      {listings ? (
        <Listings listings={listings} currentUser={currentUser} />
      ) : (
        <p>No cars found.</p>
      )}
    </div>
  );
}
