import prisma from "../libs/prismadb";
import Listing from "../components/Listing";
import getCurrentUser from "../actions/getCurrentUser";
//import Head from "next/head";

export default async function Home() {
  const listings = await prisma.listing.findMany();
  const count = await prisma.listing.count();
  const currentUser = await getCurrentUser();

  return (
    <div className="m-auto mt-11 max-w-5xl ">
      {/* <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/logo.png" />
      </Head> */}
      <h2 className="text-md font-bold pt-5 w-max inline-block">
        Featured Auctions
      </h2>
      <span className="text-sm"> ({count})</span>
      {listings ? (
        <ul className="grid grid-cols-3 gap-5 py-5">
          {listings.map((listing) => (
            <li
              key={listing.id}
              className="mb-16 border rounded-md shadow-md shadow-gray-400"
            >
              <Listing
                id={listing.id}
                year={listing.year}
                make={listing.make}
                model={listing.model}
                miles={listing.miles}
                price={listing.price}
                description={listing.description}
                watchersIds={listing.watchersIds}
                currentUser={currentUser?.id as string}
              />
            </li>
          ))}
        </ul>
      ) : (
        <p>No cars found.</p>
      )}
    </div>
  );
}
