//"use client";

import prisma from "../../libs/prismadb";
import Head from "next/head";
import Image from "next/image";
import { Params } from "next/dist/shared/lib/router/utils/route-matcher";
import Title from "@/app/components/Title";
import Form from "../components/Form";
import Description from "../components/Description";
import getCurrentUser from "@/app/actions/getCurrentUser";
import Body from "../components/Body";

const Listing = async ({ params }: Params) => {
  const { id } = params;

  const currentUser = await getCurrentUser();

  const listing = await prisma.listing.findUnique({
    where: {
      id: id as string,
    },
  });

  if (!listing) {
    console.error("Error fetching listing:", id);
    return;
  }

  const { year, make, model, miles, price, location, description } = listing;

  return (
    <div className="m-auto mt-11 flex max-w-5xl">
      <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className="w-full px-2 lg:w-10/12 lg:pl-0">
        <Title year={year} make={make} model={model} large />
        <div className="flex flex-col justify-between gap-5 rounded-t lg:rounded-l">
          <div className="rounded-md shadow-md flex justify-between shadow-gray-400">
            <Image
              src="/images/default-vehicle-image.png"
              alt="Vehicle Image"
              width={400}
              height={200}
              className="w-full rounded-l-md object-cover"
            />
          </div>
          <Description description={description} />
        </div>

        <div>
          {!currentUser && (
            <p className="text-red-500">Please log in to leave a comment</p>
          )}
          {currentUser && (
            <>
              <h1>Comments and Bids</h1>
              <Form listingId={id} />
            </>
          )}
        </div>
        <Body listingId={id} />
        {/*<VehicleListing />*/}
      </main>
      <aside className="hidden md:block md:w-2/12 md:pr-2 pt-[4.25rem]">
        <ul className="rounded-md bg-gray-400 p-2 h-[378px]">
          <li>Miles: {miles}</li>
          <li>Price: ${price}</li>
          <li>Location: {location}</li>
        </ul>
        <h1 className="font-bold">Similar Auctions</h1>
      </aside>
    </div>
  );
};

export default Listing;
