//"use client";

import prisma from "../../libs/prismadb";
import Head from "next/head";
import Image from "next/image";
import { Params } from "next/dist/shared/lib/router/utils/route-matcher";
import Title from "@/app/components/Title";

const Listing = async ({ params }: Params) => {
  const { id } = params;

  console.log("LISTING ID: ", id);

  const listing = await prisma.listing.findUnique({
    where: {
      id: id as string,
    },
  });

  if (!listing) {
    console.error("Error fetching listing:", id);
    return;
  }

  const { year, make, model, miles, price, description } = listing;

  return (
    <div className="m-auto mt-11 flex max-w-5xl gap-5">
      <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <main className="w-full px-2 md:w-4/5 md:pr-0 lg:w-10/12 lg:pl-0">
        <Title year={year} make={make} model={model} large />
        <div className="flex flex-col justify-between gap-5 rounded-t lg:rounded-l">
          <div className="rounded-md shadow-md flex justify-between shadow-gray-400">
            <Image
              src="/images/default-vehicle-image.png"
              alt="Vehicle Image"
              width={400}
              height={200}
              className="w-full rounded-l-md object-cover"
            />
            <p className="flex w-1/4 flex-col rounded-r-md bg-gray-400 p-2">
              <span>Miles: {miles}</span>
              <span>Price: ${price}</span>
            </p>
          </div>
          <div className="mb-2 p-2 border shadow-md rounded-md shadow-gray-400">
            <ul>
              <li>{description}</li>
              <li>{description}</li>
            </ul>
          </div>
        </div>

        <div>
          <h1>Chat app</h1>
        </div>
        {/*<VehicleListing />*/}
      </main>
    </div>
  );
};

export default Listing;
