"use client";

//import type { FormEvent } from "react";
import Head from "next/head";
import { FieldValues, SubmitHandler, useForm } from "react-hook-form";
import Input from "@/app/components/inputs/Input";
import axios from "axios";
import toast from "react-hot-toast";
//import { useSession } from "next-auth/react";
import { useState } from "react";

// interface FormElements extends HTMLFormControlsCollection {
//   make: HTMLInputElement;
//   model: HTMLInputElement;
//   year: HTMLInputElement;
//   miles: HTMLInputElement;
//   price: HTMLInputElement;
//   description: HTMLTextAreaElement;
// }

// interface Form extends HTMLFormElement {
//   readonly elements: FormElements;
// }

// function validateForm(e: FormEvent<Form>): void {
//   const make: string = e.currentTarget.elements.make.value;
//   const model: string = e.currentTarget.elements.model.value;
//   const description: string = e.currentTarget.elements.description.value;

//   const year: number = parseInt(e.currentTarget.elements.year.value);
//   const miles: number = parseInt(e.currentTarget.elements.miles.value);
//   const price: number = parseInt(e.currentTarget.elements.price.value);

//   if (
//     make === "" ||
//     model === "" ||
//     year === null ||
//     miles === null ||
//     price === null ||
//     description === ""
//   ) {
//     alert("Enter missing info!");
//     e.preventDefault();
//   }
// }

function SubmitVehicle() {
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<FieldValues>({
    defaultValues: {
      year: 2000,
      make: "",
      model: "",
      miles: 20,
      price: 20,
      location: "Miami, FL",
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    },
  });

  const onSubmit: SubmitHandler<FieldValues> = (data) => {
    setIsLoading(true);
    console.log("Client Data: ", data);
    axios
      .post("/api/new-listing", data)
      .then((res) => {
        console.log(res);
      })
      .catch(() => toast.error("Something went wrong!"))
      .finally(() => setIsLoading(false));
  };
  return (
    <div className=".container m-auto mt-12 flex max-w-5xl flex-col px-2">
      <Head>
        <title>Car Auctions</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col flex-nowrap md:w-3/4">
        <h2 className="pb-4 pt-8">Enter your vehicle information</h2>
        <form
          className="flex flex-col flex-nowrap"
          name="submit"
          onSubmit={handleSubmit(onSubmit)}
        >
          <Input
            // className="mb-5 h-8 w-full md:w-52 rounded border"
            type="text"
            id="make"
            label="Make"
            register={register}
            //name="make"
            errors={errors}
            disabled={isLoading}
          />

          <Input
            //className="mb-5 h-8 w-full md:w-52 rounded border"
            type="text"
            id="model"
            label="Model"
            register={register}
            //name="model"
            errors={errors}
            disabled={isLoading}
          />

          <Input
            //className="mb-5 h-8 w-full md:w-52 rounded border"
            type="number"
            id="year"
            label="Year"
            register={register}
            //name="year"
            errors={errors}
            disabled={isLoading}
          />

          <Input
            //className="mb-5 h-8 w-full md:w-52 rounded border"
            type="number"
            id="miles"
            label="Miles"
            register={register}
            //name="miles"
            errors={errors}
            disabled={isLoading}
          />

          <Input
            //className="mb-5 h-8 w-full md:w-52 rounded border"
            type="number"
            id="price"
            label="Price"
            register={register}
            //name="price"
            errors={errors}
            disabled={isLoading}
          />

          <Input
            //className="mb-5 h-8 w-full md:w-52 rounded border"
            type="text"
            id="location"
            label="Location"
            register={register}
            //name="location"
            errors={errors}
            disabled={isLoading}
          />

          <label className="w-full md:w-52 pb-3" htmlFor="description">
            Description
          </label>
          <textarea
            className="mb-5 h-32 w-full resize-none rounded border md:w-96"
            id="description"
            //name="description"
            {...register("description", { required: true })}
          />

          <label className="pb-3" htmlFor="images">
            Drag images below or{" "}
            <button id="btn_browse" disabled>
              BROWSE
            </button>
          </label>
          <textarea
            className="mb-5 h-32 w-full resize-none rounded border border-dashed md:w-96"
            id="images"
            name="images"
            disabled
          />

          <button
            type="submit"
            className="hover:bg-gray-100 rounded transition"
          >
            SUBMIT
          </button>
        </form>
      </main>
      <aside>
        <h2 className="pb-4 pt-8">Recently Sold</h2>
        <div className="recently-sold"></div>
      </aside>
    </div>
  );
}

export default SubmitVehicle;
